---
title: "Golang defer과 panic - Go series(12)"

categories:
  - Golang
tags:
  - [language, tutorial]

toc: true
toc_sticky: true

last_modified_at: 2021-02-01T23:38:00
---

![image](https://user-images.githubusercontent.com/37994634/105621623-ed7f4b00-5e4c-11eb-9c3d-53a3b52b289a.png){: width:350 height:250}

## 지연실행을 해주는 defer

defer 키워드는 특정 문장 또는 함수를 나중에 실행되게 한다.(호출 된 함수의 마지막에 실행된다) 일반적으로 defer는 `C#, java` 에서의 `finally`처럼 사용된다.

```golang
package main

import "os"

func main(){
    read_file,err := os.Open("C:\\g\\a.txt")
    if err!=nil{
        println(err)
    }
    defer read_file.Close()

    bytes := make([]byte, 1024)
    read_file.read(bytes)
    println(bytes)
}
```

## panic !?!?

현재 함수의 실행을 즉시 멈추고 현재 함수 바디 내에 존재하는 defer을 모두 실행하고 즉시 리턴하게 된다.  
이 panic은 특이하게 상위 함수까지도 적용이 되고 마지막에 프로그램이 에러를 내고 종료하게 된다.

```golang
package main

import "os"

func main() {
    // 잘못된 파일명을 넣음
    openFile("Invalid.txt")

    // openFile() 안에서 panic이 실행되면
    // 아래 println 문장은 실행 안됨
    println("Done")
}

func openFile(fn string) {
    f, err := os.Open(fn)
    if err != nil {
        panic(err)
    }

    defer f.Close()
}
```

## recover! -> 패닉을 반대로

recover이 defer 안에 있을 시에는 현 함수가 끝난 뒤 상위 함수에서는 defer만 실행되지 않고 일반적으로 진행이 된다.

```golang
package main

import (
    "fmt"
    "os"
)

func main() {
    // 잘못된 파일명을 넣음
    openFile("Invalid.txt")

    // recover에 의해
    // 이 문장 실행됨
    println("Done")
}

func openFile(fn string) {
    // defer 함수. panic 호출시 실행됨
    defer func() {
        if r := recover(); r != nil {
            fmt.Println("OPEN ERROR", r)
        }
    }()

    f, err := os.Open(fn)
    if err != nil {
        panic(err)
    }

    defer f.Close()
}
```
